### ISSUE TITLE
Please update the symbols

### ISSUE THREAD

**Issue by gokhantaskan** [talgautb/postcss-currency#2]
This is the compiled version with postCSS. Most of the necessary symbols are **not converted**. Could you please update the package?

![2019-02-23_13-49-39](https://user-images.githubusercontent.com/45636599/53285477-9826f480-3772-11e9-8d24-14e56837677d.png)

**Comment by talgautb** [comment]
@gokhantaskan i use only [official](https://github.com/talgautb/typographic-currency-db/blob/master/index.js) currency symbols
but if you have some ideas, feel free to comment

**Comment by gokhantaskan** [comment]
Thank you for your answer! I did not see the js file which contains the symbols.

I'm looking for the symbols from that website: [https://www.xe.com/symbols.php](https://www.xe.com/symbols.php)

--
₺ : Turkish lira (TRY) for example must be in the symbol's file.

**Comment by talgautb** [comment]
@gokhantaskan update plugin, and db, thanks
