### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by talgautb** [talgautb/postcss-currency#5]
after update dependencies (#3) build is broken (https://travis-ci.org/talgautb/postcss-currency)

**Comment by arturparkhisenko** [comment]
@talgautb I can work on this for the Hacktoberfest ;) will submit PR soon.

**Comment by arturparkhisenko** [comment]
@talgautb changes are ready, I thought it makes sense to make 2 PRs for two releases. I'm already **done** with v2 PR (breaking changes, like postcss v8 support and others), and will prepare v1 PR with a patch to make it work for everyone who is using something like `^1.x.x` and etc. I'm currently waiting for your feedback on the `typographic-currency-db` project PR, please check it when you have a free minute. Thanks.

**Comment by talgautb** [comment]
we have still the same [problem](https://travis-ci.org/talgautb/postcss-currency)

**Comment by arturparkhisenko** [comment]
@talgautb Thanks, I see, gulp-mocha uses the spread operator, then I'll consider other options to solve that. Thanks. I'll run such a test next time.
The test I did I've checked the app code, and from es6 features we're used only the `let/const` and arrow functions.

**Comment by arturparkhisenko** [comment]
@talgautb I've checked, it's in the changelog of gulp-mocha: `Require Node.js 8 and Gulp 4`, so it means, we have two options: 1. drop node 6, and support 8+. 2. downgrade major versions for gulp and mocha-gulp. Considering that we want to have `v1` working without breaking changes I would go with option 2. In the v2 we can incorporate those changes back.

**Comment by arturparkhisenko** [comment]
@talgautb after all checks found that two dependencies also dropped Node.js v6, after that change I did run the test on it to verify that for the new PR.
